/*
 * This file is generated by jOOQ.
 */
package se4med.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import se4med.jooq.tables.Application;
import se4med.jooq.tables.Doctor;
import se4med.jooq.tables.Doctorapp;
import se4med.jooq.tables.Doctorpatient;
import se4med.jooq.tables.Patient;
import se4med.jooq.tables.Patientdoc;
import se4med.jooq.tables.Project;
import se4med.jooq.tables.ResultNotRegistered;
import se4med.jooq.tables.Results;
import se4med.jooq.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Se4med extends SchemaImpl {

    private static final long serialVersionUID = 1864136135;

    /**
     * The reference instance of <code>se4med</code>
     */
    public static final Se4med SE4MED = new Se4med();

    /**
     * The table <code>se4med.application</code>.
     */
    public final Application APPLICATION = se4med.jooq.tables.Application.APPLICATION;

    /**
     * The table <code>se4med.doctor</code>.
     */
    public final Doctor DOCTOR = se4med.jooq.tables.Doctor.DOCTOR;

    /**
     * The table <code>se4med.doctorapp</code>.
     */
    public final Doctorapp DOCTORAPP = se4med.jooq.tables.Doctorapp.DOCTORAPP;

    /**
     * The table <code>se4med.doctorpatient</code>.
     */
    public final Doctorpatient DOCTORPATIENT = se4med.jooq.tables.Doctorpatient.DOCTORPATIENT;

    /**
     * The table <code>se4med.patient</code>.
     */
    public final Patient PATIENT = se4med.jooq.tables.Patient.PATIENT;

    /**
     * The table <code>se4med.patientdoc</code>.
     */
    public final Patientdoc PATIENTDOC = se4med.jooq.tables.Patientdoc.PATIENTDOC;

    /**
     * The table <code>se4med.project</code>.
     */
    public final Project PROJECT = se4med.jooq.tables.Project.PROJECT;

    /**
     * The table <code>se4med.result_not_registered</code>.
     */
    public final ResultNotRegistered RESULT_NOT_REGISTERED = se4med.jooq.tables.ResultNotRegistered.RESULT_NOT_REGISTERED;

    /**
     * The table <code>se4med.results</code>.
     */
    public final Results RESULTS = se4med.jooq.tables.Results.RESULTS;

    /**
     * The table <code>se4med.user</code>.
     */
    public final User USER = se4med.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Se4med() {
        super("se4med", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Application.APPLICATION,
            Doctor.DOCTOR,
            Doctorapp.DOCTORAPP,
            Doctorpatient.DOCTORPATIENT,
            Patient.PATIENT,
            Patientdoc.PATIENTDOC,
            Project.PROJECT,
            ResultNotRegistered.RESULT_NOT_REGISTERED,
            Results.RESULTS,
            User.USER);
    }
}
