/*
 * This file is generated by jOOQ.
 */
package se4med.jooq;


import javax.annotation.Generated;

import se4med.jooq.tables.Application;
import se4med.jooq.tables.Doctor;
import se4med.jooq.tables.Doctorapp;
import se4med.jooq.tables.Doctorpatient;
import se4med.jooq.tables.Patient;
import se4med.jooq.tables.Patientdoc;
import se4med.jooq.tables.Project;
import se4med.jooq.tables.ResultNotRegistered;
import se4med.jooq.tables.Results;
import se4med.jooq.tables.User;


/**
 * Convenience access to all tables in se4med
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>se4med.application</code>.
     */
    public static final Application APPLICATION = se4med.jooq.tables.Application.APPLICATION;

    /**
     * The table <code>se4med.doctor</code>.
     */
    public static final Doctor DOCTOR = se4med.jooq.tables.Doctor.DOCTOR;

    /**
     * The table <code>se4med.doctorapp</code>.
     */
    public static final Doctorapp DOCTORAPP = se4med.jooq.tables.Doctorapp.DOCTORAPP;

    /**
     * The table <code>se4med.doctorpatient</code>.
     */
    public static final Doctorpatient DOCTORPATIENT = se4med.jooq.tables.Doctorpatient.DOCTORPATIENT;

    /**
     * The table <code>se4med.patient</code>.
     */
    public static final Patient PATIENT = se4med.jooq.tables.Patient.PATIENT;

    /**
     * The table <code>se4med.patientdoc</code>.
     */
    public static final Patientdoc PATIENTDOC = se4med.jooq.tables.Patientdoc.PATIENTDOC;

    /**
     * The table <code>se4med.project</code>.
     */
    public static final Project PROJECT = se4med.jooq.tables.Project.PROJECT;

    /**
     * The table <code>se4med.result_not_registered</code>.
     */
    public static final ResultNotRegistered RESULT_NOT_REGISTERED = se4med.jooq.tables.ResultNotRegistered.RESULT_NOT_REGISTERED;

    /**
     * The table <code>se4med.results</code>.
     */
    public static final Results RESULTS = se4med.jooq.tables.Results.RESULTS;

    /**
     * The table <code>se4med.user</code>.
     */
    public static final User USER = se4med.jooq.tables.User.USER;
}
