/*
 * This file is generated by jOOQ.
 */
package se4med.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import se4med.jooq.Indexes;
import se4med.jooq.Keys;
import se4med.jooq.Se4med;
import se4med.jooq.tables.records.DoctorappRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Doctorapp extends TableImpl<DoctorappRecord> {

    private static final long serialVersionUID = 208886644;

    /**
     * The reference instance of <code>se4med.doctorapp</code>
     */
    public static final Doctorapp DOCTORAPP = new Doctorapp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DoctorappRecord> getRecordType() {
        return DoctorappRecord.class;
    }

    /**
     * The column <code>se4med.doctorapp.emaildoctor</code>. questa tabella mette in relazione il dottore e le applicazioni.
Il dottore può consultare i dati delle applicazioni per le quali si è registrato

emaildoctor identifica il dottore -&gt; FK

se l'email della tabella doctor viene cancellata/modificata, si cancellano/modificano tutti i record che contengono quel valore
     */
    public final TableField<DoctorappRecord, String> EMAILDOCTOR = createField("emaildoctor", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "questa tabella mette in relazione il dottore e le applicazioni.\nIl dottore può consultare i dati delle applicazioni per le quali si è registrato\n\nemaildoctor identifica il dottore -> FK\n\nse l'email della tabella doctor viene cancellata/modificata, si cancellano/modificano tutti i record che contengono quel valore");

    /**
     * The column <code>se4med.doctorapp.idapp</code>. identifica l'applicazione per la quale il dottore è abilitato a consultare i dati -&gt; FK

se l'id della tabella application viene aggiornato, viene aggiornato anche idapp
se l'id della tabella application viene cancellato e c'è un record che contiene quell'id, non viene permessa la cancellazione dell'applicazione
     */
    public final TableField<DoctorappRecord, String> IDAPP = createField("idapp", org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "identifica l'applicazione per la quale il dottore è abilitato a consultare i dati -> FK\n\nse l'id della tabella application viene aggiornato, viene aggiornato anche idapp\nse l'id della tabella application viene cancellato e c'è un record che contiene quell'id, non viene permessa la cancellazione dell'applicazione");

    /**
     * Create a <code>se4med.doctorapp</code> table reference
     */
    public Doctorapp() {
        this(DSL.name("doctorapp"), null);
    }

    /**
     * Create an aliased <code>se4med.doctorapp</code> table reference
     */
    public Doctorapp(String alias) {
        this(DSL.name(alias), DOCTORAPP);
    }

    /**
     * Create an aliased <code>se4med.doctorapp</code> table reference
     */
    public Doctorapp(Name alias) {
        this(alias, DOCTORAPP);
    }

    private Doctorapp(Name alias, Table<DoctorappRecord> aliased) {
        this(alias, aliased, null);
    }

    private Doctorapp(Name alias, Table<DoctorappRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Doctorapp(Table<O> child, ForeignKey<O, DoctorappRecord> key) {
        super(child, key, DOCTORAPP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Se4med.SE4MED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DOCTORAPP_DOCTORAPP_IDX, Indexes.DOCTORAPP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DoctorappRecord> getPrimaryKey() {
        return Keys.KEY_DOCTORAPP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DoctorappRecord>> getKeys() {
        return Arrays.<UniqueKey<DoctorappRecord>>asList(Keys.KEY_DOCTORAPP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DoctorappRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DoctorappRecord, ?>>asList(Keys.EMAILDOCTORDOCTORAPP, Keys.APPDOCTOR);
    }

    public Doctor doctor() {
        return new Doctor(this, Keys.EMAILDOCTORDOCTORAPP);
    }

    public Application application() {
        return new Application(this, Keys.APPDOCTOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Doctorapp as(String alias) {
        return new Doctorapp(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Doctorapp as(Name alias) {
        return new Doctorapp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Doctorapp rename(String name) {
        return new Doctorapp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Doctorapp rename(Name name) {
        return new Doctorapp(name, null);
    }
}
