/*
 * This file is generated by jOOQ.
 */
package se4med.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import se4med.jooq.Indexes;
import se4med.jooq.Keys;
import se4med.jooq.Se4med;
import se4med.jooq.tables.records.DoctorpatientRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Doctorpatient extends TableImpl<DoctorpatientRecord> {

    private static final long serialVersionUID = -130068464;

    /**
     * The reference instance of <code>se4med.doctorpatient</code>
     */
    public static final Doctorpatient DOCTORPATIENT = new Doctorpatient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DoctorpatientRecord> getRecordType() {
        return DoctorpatientRecord.class;
    }

    /**
     * The column <code>se4med.doctorpatient.emaildoctor</code>. questa tabella indica per ogni utente quale dottore può consultare i dati delle applicazioni, inoltre per ogni dottore indica quale applicazioni può consultare.

dottore che può consultare i dati delle app -&gt; FK

se l'email della tabella doctor viene cancellata/modificata, si cancellano/modificano tutti i record che contengono quel valore
     */
    public final TableField<DoctorpatientRecord, String> EMAILDOCTOR = createField("emaildoctor", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "questa tabella indica per ogni utente quale dottore può consultare i dati delle applicazioni, inoltre per ogni dottore indica quale applicazioni può consultare.\n\ndottore che può consultare i dati delle app -> FK\n\nse l'email della tabella doctor viene cancellata/modificata, si cancellano/modificano tutti i record che contengono quel valore");

    /**
     * The column <code>se4med.doctorpatient.emailpatient</code>. email utente per identificare l'utente che autorizza il dottore -&gt; FK

se l'email della tabella user viene cancellata/modificata, si cancellano/modificano tutti i record che contengono quel valore
     */
    public final TableField<DoctorpatientRecord, String> EMAILPATIENT = createField("emailpatient", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "email utente per identificare l'utente che autorizza il dottore -> FK\n\nse l'email della tabella user viene cancellata/modificata, si cancellano/modificano tutti i record che contengono quel valore");

    /**
     * The column <code>se4med.doctorpatient.username</code>. username per identificare l'utete che autorizza il dottore in modo univoco -&gt; FK

se lo user della tabella user viene cancellata/modificata, si cancellano/modificano tutti i record che contengono quel valore
     */
    public final TableField<DoctorpatientRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "username per identificare l'utete che autorizza il dottore in modo univoco -> FK\n\nse lo user della tabella user viene cancellata/modificata, si cancellano/modificano tutti i record che contengono quel valore");

    /**
     * The column <code>se4med.doctorpatient.idapp</code>. idapp per la quale il dottore è autorizzato a visualizzare i dati del paziente -&gt; FK

se l'id della tabella application viene aggiornato, viene aggiornato anche idapp
se l'id della tabella application viene cancellato e c'è un record che contiene quell'id, non viene permessa la cancellazione dell'applicazione

     */
    public final TableField<DoctorpatientRecord, String> IDAPP = createField("idapp", org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "idapp per la quale il dottore è autorizzato a visualizzare i dati del paziente -> FK\n\nse l'id della tabella application viene aggiornato, viene aggiornato anche idapp\nse l'id della tabella application viene cancellato e c'è un record che contiene quell'id, non viene permessa la cancellazione dell'applicazione\n");

    /**
     * Create a <code>se4med.doctorpatient</code> table reference
     */
    public Doctorpatient() {
        this(DSL.name("doctorpatient"), null);
    }

    /**
     * Create an aliased <code>se4med.doctorpatient</code> table reference
     */
    public Doctorpatient(String alias) {
        this(DSL.name(alias), DOCTORPATIENT);
    }

    /**
     * Create an aliased <code>se4med.doctorpatient</code> table reference
     */
    public Doctorpatient(Name alias) {
        this(alias, DOCTORPATIENT);
    }

    private Doctorpatient(Name alias, Table<DoctorpatientRecord> aliased) {
        this(alias, aliased, null);
    }

    private Doctorpatient(Name alias, Table<DoctorpatientRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Doctorpatient(Table<O> child, ForeignKey<O, DoctorpatientRecord> key) {
        super(child, key, DOCTORPATIENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Se4med.SE4MED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DOCTORPATIENT_APPUSER_IDX, Indexes.DOCTORPATIENT_EMAILUSER_IDX, Indexes.DOCTORPATIENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DoctorpatientRecord> getPrimaryKey() {
        return Keys.KEY_DOCTORPATIENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DoctorpatientRecord>> getKeys() {
        return Arrays.<UniqueKey<DoctorpatientRecord>>asList(Keys.KEY_DOCTORPATIENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DoctorpatientRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DoctorpatientRecord, ?>>asList(Keys.EMAILDOCTOR, Keys.EMAILUSER, Keys.APPUSERDOCTOR);
    }

    public Doctor doctor() {
        return new Doctor(this, Keys.EMAILDOCTOR);
    }

    public Patient patient() {
        return new Patient(this, Keys.EMAILUSER);
    }

    public Application application() {
        return new Application(this, Keys.APPUSERDOCTOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Doctorpatient as(String alias) {
        return new Doctorpatient(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Doctorpatient as(Name alias) {
        return new Doctorpatient(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Doctorpatient rename(String name) {
        return new Doctorpatient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Doctorpatient rename(Name name) {
        return new Doctorpatient(name, null);
    }
}
